### ISSUE TITLE
generating tab completion for HasDynamicAttrs

### ISSUE THREAD

**Issue by chrismacklin** [martinisgroup/pylabrad#101]
How are tab completions generated for ServerWrapper (or for that matter anything that inherits from HasDynamicAttrs)?  I'm familiar with defining a `__dir__` method ( http://ipython.org/ipython-doc/dev/config/integrating.html ), but this doesn't appear to happen anywhere.

My use case is an object that wraps a ServerWrapper, and I'd like tab completion on this object to include all of the attributes of the ServerWrapper itself, but I cannot determine what method is called on ServerWrapper to generate them.

**Comment by DanielSank** [comment]
Isn't this a question of implementing the methods ipython wants, as described in the link in OP?

**Comment by maffoo** [comment]
There's a method called `_getAttributeNames`: https://github.com/martinisgroup/pylabrad/blob/master/labrad/client.py#L222

This was how it used to work, back in like the ipython 0.10 days. I think that method name came from an old tool called pycrust, and apparently ipython still supports it, even if the recommended way to do this has changed. Feel free to make a change and submit a PR.

**Comment by chrismacklin** [comment]
Digging in to this slightly deeper, it looks as if _getAttributeNames is actually a lot nicer than implementing __dir__ (though totally undocumented at this point).  The problem with implementing __dir__ is that __dir__ must return *all* of the attributes, not just the dynamically-added attributes, leading to annoying hacks like
```python
def __dir__(self):
    return sorted(set((dir(type(self)) + list(self.__dict__) +
                  self._get_dynamic_attributes()))
```
because once you have implemented __dir__ you can't call dir(self) to get the static attributes as that results in a recursion loop.

It looks as if whatever calls _getAttributeNames is working behind the scenes to get all of the static attributes and then combining them with the list returned by _getAttributeNames.  Implementing _getAttributeNames for my wrapper class seems to work fine, so I'm closing this.
