### ISSUE TITLE
Device locking seems to be completely broken

### ISSUE THREAD

**Issue by chrismacklin** [martinisgroup/pylabrad#106]
Locking a device without a specified timeout does not perpetually lock the device, as one might expect from the setting description
```
Accepts:
    : Lock the selected device
    v[s]: Lock for specified time
```
but actually just locks it for the time `devices.LOCK_TIMEOUT = 10`.

Further, trying to specify a timeout throws an error which I believe is due to a bug here:
https://github.com/martinisgroup/pylabrad/blob/062cd5188ee8ac5abcf2a29c9edd1ee4e93e8bde/labrad/devices.py#L52-L56
`timeout` is passed in to this method with units but the method expects a dimensionless value (really just a bare number).  Easy fix but I don't know whether it would be better to unpack the value in the `lock_device` setting or in the `DeviceWrapper` definition.  I'd assume in the latter as `lock_device` may be overridden in some child classes.

**Comment by DanielSank** [comment]
We fixed a major problem with the way units are handled in pylabrad a while back. It looks like this is just a loose end. PR to fix that problem would be much appreciated.

I would rename `timeout` to `timeout_s` to indicate the necessary units, and then put the unit conversion where `lock` is called.

**Comment by chrismacklin** [comment]
Fixed in #107.  It still would be nice to be able to lock a device in a context indefinitely, but some unforseen error condition could leave stale locks so I'll settle for setting large values for now.

**Comment by DanielSank** [comment]
@chrismacklin indefinite locks seem unwise due to the fact that we're dealing with a network.

**Comment by chrismacklin** [comment]
Certainly. The revised setting documentation to reflect that lock_device with no argument is just locking for a default time is enough of an improvement.  I don't have a use case in mind for a perpetual lock, and I'm not even sure we'll end up using device locks at all.  This all came up because I was demoing labrad for someone today and attempted to demonstrate locking a device and it failed :)
