### ISSUE TITLE
type inference in complex nested types fails

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/pylabrad#3]
`[([],),([5.0],)]` does not flatten. See test_types.py.

This has to do with the `LRNone` class and how types are considered to be " equal to or more specific than" other types.

**Comment by maffoo** [comment]
This seems to be fixed by recent changes to type inference in types.py:
```python
In [1]: import labrad.types as T

In [2]: T.flatten([([],),([5.0],)])
Out[2]: 
('\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x01@\x14\x00\x00\x00\x00\x00\x00',
 LRList(LRCluster(LRList(LRValue(''), depth=1)), depth=1))
```
