### ISSUE TITLE
coveralls

### ISSUE THREAD

**Issue by jayich** [martinisgroup/pylabrad#56]
I noticed that travis is gaining a lot of traction.  That is exciting.  

Coveralls seems like a decent option to consider for displaying test coverage status:

https://coveralls.io/

Qutip (https://github.com/qutip/qutip) uses this and travis.  I'll look into setting this up with another repository, and if there is interest it could be added to pylabrad.  Someone with better sys-admin skills could probably do this pretty quickly.

**Comment by DanielSank** [comment]
LGTM, but I don't have experience with coverage services.
