### ISSUE TITLE
Unflattening array of complex numbers loses units

### ISSUE THREAD

**Issue by maffoo** [martinisgroup/pylabrad#64]
Currently, these unflatten by default as numpy arrays with complex128 as the dtype, but no units. Contrast this with arrays of real values which unflatten into ValueArray and so preserve the unit information.

**Comment by DanielSank** [comment]
Should I regard this as something to fix or is this in your court?

**Comment by ejeffrey** [comment]
Nitpick: arrays of real numbers unflatten (or should) to
DimensionlessArray, which has both the ValueArray/WithUnit API and the
numpy API so it can work transparently with numpy but still works with code
that expect units.  complex numbers should do the same.
