### ISSUE TITLE
cxn.registry.del is treated as a syntax error

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/pylabrad#69]
I'm on Ubuntu 14

Can anyone else reproduce this error on their system?

**Comment by pomalley** [comment]
workaround: `cxn.registry['del']`

**Comment by DanielSank** [comment]
Thanks, @pomalley, I was trying to figure out a workaround like that :-)

**Comment by pomalley** [comment]
Yeah, I remember running into this before, but I don't remember in what context.

Surely you want to use the registry wrapper, anyway?

**Comment by DanielSank** [comment]
Oh, uh, yeah, I guess I do want that.

**Comment by ejeffrey** [comment]
Yes, this is a known issue.  del is a keyword in python so you can't use it
as an identifier, including an attribute name.  I actually thought pylabrad
special cased methods named del and renamed them, but apparently not.

**Comment by ejeffrey** [comment]
OK, just looked into this.  We do name mangling to avoid making illegal
identifier names (i.e., starts with a digit, contains spaces or minus
signs), and to avoid confligting with existing static attributes of server
wrappers, but not to avoid keywords.

I have a patch to fix this.

**Comment by ejeffrey** [comment]
closed by #70.
