### ISSUE TITLE
Can not import ValueArray

### ISSUE THREAD

**Issue by hoiiochun** [martinisgroup/pylabrad#77]
When we try
```
from labrad.units import ValueArray
```
we get an error message:
```
ImportError: cannot import name ValueArray
```
On most recent master branch. Note that this works on another computer also on most recent master branch. Pylabrad is in PYTHONPATH environment variable.

-@hoiiochun and @jwenner

**Comment by jwenner** [comment]
Fixed. Only thought we were on master branch. Actually on packetdump branch. Switching to most recent master branch fixed this.

**Comment by pomalley** [comment]
Yay!
