### ISSUE TITLE
hdf5 support

### ISSUE THREAD

**Issue by chrismacklin** [martinisgroup/pylabrad#99]
I asked Dan about this; he said, "actually the code is already written but sitting in [ @ejeffrey ]'s branch."

**Comment by maffoo** [comment]
See the [u/ejeffrey/hdf5_data](https://github.com/martinisgroup/servers/tree/u/ejeffrey/hdf5_data) branch in the servers repo. If you'd like to track this, please open an issue there where the data vault code live.
